// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwqntrczavpntsqvqvzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cW50cmN6YXZwbnRzcXZxdnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NTY5NjUsImV4cCI6MjA1MTIzMjk2NX0.-e9sjIuXhhD30SH8EP33_wTdFCkz-FSmHxaZtcT57K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);